---
- name: Reload Apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: reloaded

- name: Restart Apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted
